import React from 'react';
import './App.css';
import Room from './pages/Room';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import SearchBar from './components/SearchBar/SearchBar';

function App() {
    const locations = [
        "Academy Hall AUD",
        "Alumni Sports and Rec Center 209",
        "Alumni Sports and Rec Center 407",
        "Amos Eaton Hall 214",
        "Amos Eaton Hall 215",
        "Amos Eaton Hall 216",
        "Amos Eaton Hall 217",
        "Biotechnology and Interdis Bld AUDITORIUM",
        "Carnegie Building 101",
        "Carnegie Building 102",
        "Carnegie Building 106",
        "Carnegie Building 113",
        "Carnegie Building 201",
        "Carnegie Building 205",
        "Carnegie Building 206",
        "Carnegie Building 208",
        "Carnegie Building 210",
        "Cogswell Laboratory 113",
        "Darrin Communications Center 174",
        "Darrin Communications Center 232",
        "Darrin Communications Center 235",
        "Darrin Communications Center 236",
        "Darrin Communications Center 239",
        "Darrin Communications Center 308",
        "Darrin Communications Center 318",
        "Darrin Communications Center 324",
        "Darrin Communications Center 330",
        "Darrin Communications Center 337",
        "Folsom Library",
        "Greene Building",
        "Greene Building 120",
        "Greene Building 204",
        "Greene Building STU",
        "Gurley Building",
        "Jonsson Engineering Center 1010",
        "Jonsson Engineering Center 1034",
        "Jonsson Engineering Center 1219",
        "Jonsson Engineering Center 2220",
        "Jonsson Engineering Center 3207",
        "Jonsson Engineering Center 3210",
        "Jonsson Engineering Center 3232",
        "Jonsson Engineering Center 3332",
        "Jonsson Engineering Center 4104",
        "Jonsson Engineering Center 4107",
        "Jonsson Engineering Center 4201",
        "Jonsson Engineering Center 4304",
        "Jonsson Engineering Center 4309",
        "Jonsson Engineering Center 5119",
        "Jonsson Engineering Center 5213",
        "Jonsson Engineering Center 6309",
        "Jonsson Engineering Center 6314",
        "Jonsson-Rowland Science Center",
        "Jonsson-Rowland Science Center 1W01",
        "Jonsson-Rowland Science Center 2C06",
        "Jonsson-Rowland Science Center 2C13",
        "Jonsson-Rowland Science Center 2C14",
        "Jonsson-Rowland Science Center 2C22",
        "Jonsson-Rowland Science Center 2C25",
        "Jonsson-Rowland Science Center 2C30",
        "Jonsson-Rowland Science Center 3C30",
        "Jonsson-Rowland Science Center 3W12",
        "Jonsson-Rowland Science Center 3W13",
        "Lally Hall 02",
        "Lally Hall 102",
        "Lally Hall 104",
        "Low Center for Industrial Inn. 1027",
        "Low Center for Industrial Inn. 3039",
        "Low Center for Industrial Inn. 3045",
        "Low Center for Industrial Inn. 3051",
        "Low Center for Industrial Inn. 3112",
        "Low Center for Industrial Inn. 3116",
        "Low Center for Industrial Inn. 3130",
        "Low Center for Industrial Inn. 4034",
        "Low Center for Industrial Inn. 4040",
        "Low Center for Industrial Inn. 4050",
        "Low Center for Industrial Inn. 5118",
        "Low Center for Industrial Inn. 6116",
        "Materials Research Center",
        "Materials Research Center 136",
        "Nason Hall 130",
        "Online",
        "Pittsburgh Building 4114",
        "Pittsburgh Building 4206",
        "Pittsburgh Building 5114",
        "Pittsburgh Building 5216",
        "Ricketts Building 008A",
        "Ricketts Building 203",
        "Ricketts Building 208",
        "Ricketts Building 211",
        "Ricketts Building 212",
        "Russell Sage Laboratory 1211",
        "Russell Sage Laboratory 2112",
        "Russell Sage Laboratory 2211",
        "Russell Sage Laboratory 2411",
        "Russell Sage Laboratory 2510",
        "Russell Sage Laboratory 2701",
        "Russell Sage Laboratory 2704",
        "Russell Sage Laboratory 2707",
        "Russell Sage Laboratory 2715",
        "Russell Sage Laboratory 3101",
        "Russell Sage Laboratory 3205",
        "Russell Sage Laboratory 3303",
        "Russell Sage Laboratory 3510",
        "Russell Sage Laboratory 3704",
        "Russell Sage Laboratory 3705",
        "Russell Sage Laboratory 3713",
        "Russell Sage Laboratory 4101",
        "Russell Sage Laboratory 4112",
        "Russell Sage Laboratory 4203",
        "Russell Sage Laboratory 4510",
        "Russell Sage Laboratory 4711",
        "Russell Sage Laboratory 5101",
        "Russell Sage Laboratory 5510",
        "Russell Sage Laboratory 5711",
        "Voorhees Computing Center NO",
        "Voorhees Computing Center SO",
        "Walker Laboratory",
        "Walker Laboratory 3109",
        "Walker Laboratory 3214",
        "Walker Laboratory 3222",
        "Walker Laboratory 5113",
        "Walker Laboratory 6113",
        "West Hall 110",
        "West Hall 112",
        "West Hall 113",
        "West Hall 211",
        "West Hall 214",
        "West Hall 323",
        "West Hall 326",
        "West Hall 411",
        "West Hall AUD",
        "Winslow Building 1140"
    ];        

    return (
        <Router>
            <Routes>
                <Route path="/room/:roomid" element={<Room />}/>
            </Routes>
            <SearchBar data={locations}/>
        </Router>
    );
}

export default App;
